spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/webflux}
jjwt:
  secret: ${JJWT_SECRET:4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjW}
  expiration: 2800
